#!/bin/sh

cd -P -- "$(dirname -- "$0")"

main() {
    cd src || exit

    find -- * -type f -not -path 'templates/*' | while read -r page; do
        (cd ../docs && rm -r "$page" && echo rm "$page")
    done
}

main

